feat(CN-33): Создал исходный проект согласно карточке 33
MyNameIsVladislav/AshtrayMagazine pull request #1
Opened 2021-08-20 14:03 UTC by MyNameIsVladislav

Выполнил следующие задачи:
      Создать проект с использованием встроенных средств Django
      Изучить подходы к организации структуры папок в Django проектах
      Создать scaffold приложения Django
      Настроить локализацию
      Создать виртуальное окружение
      Создать env. файл с использованием библиотеки dotenv
      Создать файл зависимостей с прописанными версиями пакетов - requirements.txt

2021-08-20 14:03 UTC, MyNameIsVladislav commented
![](https://github.trello.services/images/mini-trello-icon.png) [Scaffold](https://trello.com/c/u47zoyc5/33-scaffold)

2021-08-22 19:37 UTC, MyNameIsVladislav commented
![](https://github.trello.services/images/mini-trello-icon.png) [Настроить логирование в файлы](https://trello.com/c/sXCuCod6/32-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-%D0%BB%D0%BE%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2-%D1%84%D0%B0%D0%B9%D0%BB%D1%8B)

2021-08-23 07:48 UTC, MaxKomarenko commented
Все папки __pycache__ должны быть в игноре IDE. Тк это специфичные файлы только для твоей IDE, то добавлять это в общий gitignore избыточно. Поэтому можно воспользоваться игнором от IDE.

2021-08-23 07:52 UTC, MaxKomarenko commented
error.log должен храниться в отдельной папке с другими лог-файлами

2021-08-23 07:53 UTC, MaxKomarenko commented
Что за mainapp? Для чего он нужен?

2021-08-23 07:54 UTC, MaxKomarenko commented
Не вижу .env файла

2021-08-23 08:03 UTC, MaxKomarenko commented
Где локализация?

2021-08-23 08:05 UTC, MaxKomarenko requested changes

2021-08-23 08:05 UTC, MaxKomarenko commented on run.bat
> +python manage.py runserver
Подобного рода файлы лучше структурно собрать в отдельной директории. Ну а вообще фал для данной команды избыточен, данные команды можно ввести вручную. Поэтому нужно убрать батники.

2021-08-23 08:05 UTC, MaxKomarenko commented on mig.bat
> +python manage.py makemigrations
Аналогично run.bat

2021-08-23 08:05 UTC, MaxKomarenko commented on mainapp/tests.py
> +from django.test import TestCase
Данный файл тебе пока не нужен, удОли!

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +SECRET_KEY = 'django-insecure-tr827dnl@zu=f^^)+qblb16^-*jsmx_k+(3@m0mbr2@19gjg4b'
Это нужно вынести в енвы

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +DEBUG = True
+1

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +    'mainapp',
Рекомендую разделять отступами приложения проектные, библиотеки и внутренние библиотеки. С третьим ты пока не столкнешься.

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +        'NAME': 'postgres',
енвы +1

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +        'USER': 'postgres',
енвы +1

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +LOGGING = {
Это нужно вынести в отдельный файл в папке логирование

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +LOGGING = {
Не все логеры, описанные в карточке, добавлены в лог конфиг

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +from dotenv import load_dotenv
Вынеси это в manage.py

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +load_dotenv(os.path.join(BASE_DIR, '.env'))
manage.py

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +
Для работы с енвами используй библиотеку environ

2021-08-23 08:05 UTC, MaxKomarenko commented on core/settings.py
> +
Нужно добавить пути для медиа и статики. Добавить директорию в gitignore.

2021-08-23 08:05 UTC, MaxKomarenko commented on core/urls.py
> +]
Добавить пути для медиа и статики

2021-08-23 14:53 UTC, MaxKomarenko requested changes

2021-08-23 14:53 UTC, MaxKomarenko commented on core/settings.py
> +with open(os.path.join(BASE_DIR, 'log/logging.log'), 'r') as log:
Вынеси в py файл

2021-08-23 14:53 UTC, MaxKomarenko commented on core/settings.py
> +        'ENGINE': os.getenv('ENGINE'),
Это можно оставить, верни )

2021-08-23 18:01 UTC, MaxKomarenko requested changes
Еще роуты для медиа и статики нужно прокинуть

2021-08-23 18:01 UTC, MaxKomarenko commented on core/settings.py
> +import os
Порядок импортов погулять не вышел? PEP8 все дела

2021-08-27 12:19 UTC, merged