Cn 20
MyNameIsVladislav/AshtrayMagazine pull request #5
Opened 2021-08-31 12:31 UTC by MyNameIsVladislav

delete pycache

2021-08-31 12:54 UTC, MyNameIsVladislav commented
![](https://github.trello.services/images/mini-trello-icon.png) [[3] AuthModels](https://trello.com/c/AOB4Rgkw/20-3-authmodels)

2021-08-31 12:54 UTC, MyNameIsVladislav commented
![](https://github.trello.services/images/mini-trello-icon.png) [[3] AuthModels](https://trello.com/c/AOB4Rgkw/20-3-authmodels)

2021-09-13 11:18 UTC, MaxKomarenko requested changes

2021-09-13 11:18 UTC, MaxKomarenko commented on authapp/management/commands/update_db.py
> +class Command(BaseCommand):
Зачем это?

2021-09-13 11:18 UTC, MaxKomarenko commented on authapp/management/commands/update_db.py
> +from ...models import CustomUser, UserProfile
Не используй относительные импорты.

2021-09-13 11:18 UTC, MaxKomarenko commented on authapp/models.py
> +    phone_validator = RegexValidator(regex=r'^\+&7|1?\d{8,15}$')
Выглядит как поле модели, хотя на самом деле им не является

2021-09-13 11:18 UTC, MaxKomarenko commented on authapp/models.py
> +    @receiver(post_save, sender=CustomUser)
Не уверен, что это хорошая идея делать сигналы методами модели

2021-09-13 11:18 UTC, MaxKomarenko commented on authapp/models.py
> +            today = date.today()
Что насчет utc? И как таймзоны будут чекаться?

2021-09-13 11:18 UTC, MaxKomarenko commented on authapp/models.py
> +class CustomUser(AbstractUser):
Назови его просто User

2021-09-13 11:18 UTC, MaxKomarenko commented on authapp/admin.py
> +admin.site.register(CustomUser)
Как ты в админке резолвишь изменение login поля? Получается ты поменял его в модели, но адмнка все ще будет ждать username

2021-09-13 11:18 UTC, MaxKomarenko commented on authapp/urls.py
> +urlpatterns = []
Отступ в конце файла

2021-09-13 11:33 UTC, MaxKomarenko commented
УдОли из requirements

cobble
rich
colorama
commonmark
django-environ-2
Pygments
python-gettext
sqlparse
typing-extensions

2021-09-15 13:00 UTC, MaxKomarenko commented
Где миграция в приложении authapp?

2021-09-15 14:13 UTC, MaxKomarenko requested changes

2021-09-15 14:13 UTC, MaxKomarenko commented on authapp/models.py
> +    phone_validator = RegexValidator(regex=r'^\+&7|1?\d{8,15}$')
Сделай валидатор через класс. Наследуйся от BaseValidator из Django и реализуй по примеру MinValueValidator. Это встроенные валидаторы, можешь загуглить где их найти.

2021-09-15 14:13 UTC, MaxKomarenko commented on authapp/models.py
> +    def create_user_profile(sender, instance, created, **kwargs):
Сделай функцией вне класса

2021-09-15 14:13 UTC, MaxKomarenko commented on authapp/models.py
> +    def save_user_profile(sender, instance, **kwargs):
Сделай функциями вне класса

2021-09-15 14:13 UTC, MaxKomarenko commented on authapp/models.py
> +        if self.user.birthday:
Я бы добавил сюда проверку - if self.user and self.user.birthday:

2021-09-15 14:13 UTC, MaxKomarenko commented on authapp/admin.py
> +# Register your models here.
Удоли

2021-09-15 14:13 UTC, MaxKomarenko commented on authapp/models.py
> +# Create your models here.
Удоли

2021-09-15 14:13 UTC, MaxKomarenko commented on authapp/models.py
> +from .managers import CustomUserManager
Абсолютные

2021-09-15 14:13 UTC, MaxKomarenko commented on authapp/models.py
> +        if now() <= self.activation_key_expires:
Почему здесь не написать просто - return not now() <= self.activation_key_expires  ?

2021-09-15 14:13 UTC, MaxKomarenko commented on core/settings.py
> +from dotenv import load_dotenv
Используем только в manage.py

2021-09-15 14:13 UTC, MaxKomarenko commented on core/settings.py
> +load_dotenv(os.path.join(BASE_DIR, '.env'))
Аналогично - manage.py

2021-09-15 14:13 UTC, MaxKomarenko commented on core/settings.py
> -DEBUG = bool(os.getenv('DEBUG'))
Бери из енвов, но поставь дефолт

2021-09-15 14:13 UTC, MaxKomarenko commented on core/settings.py
>  SECRET_KEY = os.getenv('SECRET_KEY')
Берешь енв и ставишь дефолтное значение

2021-09-15 14:13 UTC, MaxKomarenko commented on core/settings.py
> +DEBUG = True
Енв - дефолтное значение

2021-09-15 14:13 UTC, MaxKomarenko commented on core/settings.py
> +AUTH_USER_MODEL = 'authapp.CustomUser'
Переименовал модель юзера

2021-09-15 14:13 UTC, MaxKomarenko commented on core/urls.py
>  if settings.DEBUG:
Верни

2021-09-15 14:13 UTC, MaxKomarenko commented on manage.py
> +from core.settings import BASE_DIR
Удоил

2021-09-15 14:13 UTC, MaxKomarenko commented on manage.py
>      """Run administrative tasks."""
Насоклько я помню по дефолту он возьмет из папки проекта, поэтому это не обязательно

2021-09-21 08:36 UTC, MaxKomarenko requested changes

2021-09-21 08:36 UTC, MaxKomarenko commented on authapp/managers.py
> +        return self.create_user(email, password, **extra_fields)
Пустая строка в конце файла где?

2021-09-21 11:56 UTC, merged